### ISSUE TITLE
Where is ShrinkFun?

### ISSUE THREAD

**Issue by 82018303kazuma** [tomguluson92/StyleGAN2_PyTorch#5]
python3 train.py
↓
error

File "/home/atsushi/Pytorch/StyleGAN2_PyTorch/network/stylegan2.py", line 41, in <module>
from utils.libs import ShrinkFun

ImportError: cannot import name 'ShrinkFun'

**Comment by 82018303kazuma** [comment]
Is ShrinkFun necessary?

**Comment by tomguluson92** [comment]
> Is ShrinkFun necessary?

Hi, I have it fixed, you can check it from `utils.libs.py`, Thank you for point that! But the network still can not converge somehow.. I still can't fix it~

**Comment by 82018303kazuma** [comment]
thank you! 
True, it does not converge.
I am also looking for the cause.

**Comment by tomguluson92** [comment]
> thank you!
> True, it does not converge.
> I am also looking for the cause.

But I am pretty sure that the network part is almost the same with the TF repo. The training process may have some flaws, if you can fix, it would be great!
